app:
  outputDir: ./output
  fileFormat: csv
  mergeMode: round_robin
  errorMode: continue_on_error
  parallelism: 5
  fetchSize: 5000
  queryTimeoutSec: 120
  progressLogEveryRows: 10000
  maxMergedRows:
  deleteOutputFilesAfterCompletion: false
  sources:
    - name: db1
      jdbcUrl: ${LOCAL_MANUAL_DB_JDBC_URL}
      username: ${LOCAL_MANUAL_DB_USERNAME}
      password: ${LOCAL_MANUAL_DB_PASSWORD}
      sqlFile: classpath:sql/source1.sql
    - name: db2
      jdbcUrl: ${LOCAL_MANUAL_DB_JDBC_URL}
      username: ${LOCAL_MANUAL_DB_USERNAME}
      password: ${LOCAL_MANUAL_DB_PASSWORD}
      sqlFile: classpath:sql/source2.sql
    - name: db3
      jdbcUrl: ${LOCAL_MANUAL_DB_JDBC_URL}
      username: ${LOCAL_MANUAL_DB_USERNAME}
      password: ${LOCAL_MANUAL_DB_PASSWORD}
      sqlFile: classpath:sql/source3.sql
    - name: db4
      jdbcUrl: ${LOCAL_MANUAL_DB_JDBC_URL}
      username: ${LOCAL_MANUAL_DB_USERNAME}
      password: ${LOCAL_MANUAL_DB_PASSWORD}
      sqlFile: classpath:sql/source4.sql
    - name: db5
      jdbcUrl: ${LOCAL_MANUAL_DB_JDBC_URL}
      username: ${LOCAL_MANUAL_DB_USERNAME}
      password: ${LOCAL_MANUAL_DB_PASSWORD}
      sqlFile: classpath:sql/source5.sql

  target:
    enabled: true
    jdbcUrl: ${LOCAL_MANUAL_DB_JDBC_URL}
    username: ${LOCAL_MANUAL_DB_USERNAME}
    password: ${LOCAL_MANUAL_DB_PASSWORD}
    table: datapool_manual_big.target_pool_big
    truncateBeforeLoad: true
