package com.sbrf.lt.platform.composeui.sql_console

import com.sbrf.lt.platform.composeui.foundation.http.ComposeHttpClient
import com.sbrf.lt.platform.composeui.model.CredentialsStatusResponse
import kotlinx.coroutines.CoroutineScope
import org.w3c.files.File

internal data class SqlConsolePageUiState(
    val ownerSessionId: String = resolveSqlConsoleOwnerSessionId(),
    val ownerTabInstanceId: String = resolveSqlConsoleOwnerTabInstanceId(),
    val editorInstance: Any? = null,
    val editorFocused: Boolean = false,
    val editorCursorLine: Int = 1,
    val selectedRecentQuery: String = "",
    val selectedFavoriteQuery: String = "",
    val credentialsStatus: CredentialsStatusResponse? = null,
    val selectedCredentialsFile: File? = null,
    val credentialsUploadInProgress: Boolean = false,
    val credentialsMessage: String? = null,
    val credentialsMessageLevel: String = "success",
    val activeOutputTab: String = "data",
    val selectedStatementIndex: Int = 0,
    val selectedResultShard: String? = null,
    val currentDataPage: Int = 1,
    val runningClockTick: Int = 0,
)

internal data class SqlConsolePageCallbacks(
    val onCheckConnections: () -> Unit,
    val onMaxRowsDraftChange: (String) -> Unit,
    val onTimeoutDraftChange: (String) -> Unit,
    val onSaveSettings: () -> Unit,
    val onToggleSource: (String, Boolean) -> Unit,
    val onCredentialsFileSelected: (File?) -> Unit,
    val onUploadCredentials: () -> Unit,
    val onRecentSelected: (String) -> Unit,
    val onFavoriteSelected: (String) -> Unit,
    val onApplyRecent: () -> Unit,
    val onApplyFavorite: () -> Unit,
    val onRememberFavorite: () -> Unit,
    val onRemoveFavorite: () -> Unit,
    val onClearRecent: () -> Unit,
    val onStrictSafetyToggle: () -> Unit,
    val onAutoCommitToggle: (Boolean) -> Unit,
    val onInsertFavoriteObject: (SqlConsoleFavoriteObject, String) -> Unit,
    val onOpenFavoriteMetadata: (SqlConsoleFavoriteObject) -> Unit,
    val onRemoveFavoriteObject: (SqlConsoleFavoriteObject) -> Unit,
    val onEditorReady: (Any) -> Unit,
    val onFocusEditor: () -> Unit,
    val onDraftSqlChange: (String) -> Unit,
    val onPageSizeChange: (Int) -> Unit,
    val onFormatSql: () -> Unit,
    val onRunCurrent: () -> Unit,
    val onRunAll: () -> Unit,
    val onStop: () -> Unit,
    val onCommit: () -> Unit,
    val onRollback: () -> Unit,
    val onExportCsv: () -> Unit,
    val onExportZip: () -> Unit,
    val onSelectStatement: (Int) -> Unit,
    val onSelectOutputTab: (String) -> Unit,
    val onSelectShard: (String?) -> Unit,
    val onSelectPage: (Int) -> Unit,
)

internal fun sqlConsolePageCallbacks(
    store: SqlConsoleStore,
    scope: CoroutineScope,
    httpClient: ComposeHttpClient,
    currentState: () -> SqlConsolePageState,
    setState: (SqlConsolePageState) -> Unit,
    currentUiState: () -> SqlConsolePageUiState,
    setUiState: (SqlConsolePageUiState) -> Unit,
    currentOutlineItem: () -> SqlScriptOutlineItem?,
    pendingManualTransaction: () -> Boolean,
    isRunning: () -> Boolean,
    exportableResult: () -> SqlConsoleQueryResult?,
    activeExportShard: () -> String?,
): SqlConsolePageCallbacks {
    val context = SqlConsolePageBindingContext(
        store = store,
        scope = scope,
        httpClient = httpClient,
        currentStateProvider = currentState,
        setStateProvider = setState,
        currentUiStateProvider = currentUiState,
        setUiStateProvider = setUiState,
        currentOutlineItem = currentOutlineItem,
        pendingManualTransaction = pendingManualTransaction,
        isRunning = isRunning,
        exportableResult = exportableResult,
        activeExportShard = activeExportShard,
    )
    val executionBindings = SqlConsoleExecutionBindings(context)
    val libraryBindings = SqlConsoleLibraryBindings(context)
    val editorBindings = SqlConsoleEditorBindings(context, executionBindings)

    return SqlConsolePageCallbacks(
        onCheckConnections = libraryBindings::checkConnections,
        onMaxRowsDraftChange = libraryBindings::updateMaxRowsDraft,
        onTimeoutDraftChange = libraryBindings::updateTimeoutDraft,
        onSaveSettings = libraryBindings::saveSettings,
        onToggleSource = libraryBindings::toggleSource,
        onCredentialsFileSelected = libraryBindings::selectCredentialsFile,
        onUploadCredentials = libraryBindings::uploadCredentials,
        onRecentSelected = libraryBindings::selectRecent,
        onFavoriteSelected = libraryBindings::selectFavorite,
        onApplyRecent = libraryBindings::applyRecent,
        onApplyFavorite = libraryBindings::applyFavorite,
        onRememberFavorite = libraryBindings::rememberFavorite,
        onRemoveFavorite = libraryBindings::removeFavorite,
        onClearRecent = libraryBindings::clearRecent,
        onStrictSafetyToggle = libraryBindings::toggleStrictSafety,
        onAutoCommitToggle = libraryBindings::toggleAutoCommit,
        onInsertFavoriteObject = { _, sql -> editorBindings.insertFavoriteObject(sql) },
        onOpenFavoriteMetadata = libraryBindings::openFavoriteMetadata,
        onRemoveFavoriteObject = libraryBindings::removeFavoriteObject,
        onEditorReady = editorBindings::onEditorReady,
        onFocusEditor = editorBindings::focusEditor,
        onDraftSqlChange = editorBindings::updateDraftSql,
        onPageSizeChange = editorBindings::updatePageSize,
        onFormatSql = executionBindings::formatSql,
        onRunCurrent = executionBindings::runCurrent,
        onRunAll = executionBindings::runAll,
        onStop = executionBindings::stop,
        onCommit = executionBindings::commit,
        onRollback = executionBindings::rollback,
        onExportCsv = executionBindings::exportCsv,
        onExportZip = executionBindings::exportZip,
        onSelectStatement = editorBindings::selectStatement,
        onSelectOutputTab = editorBindings::selectOutputTab,
        onSelectShard = editorBindings::selectShard,
        onSelectPage = editorBindings::selectPage,
    )
}
