app:
  outputDir: ./output
  fileFormat: csv
  mergeMode: plain
  errorMode: continue_on_error
  parallelism: 5
  fetchSize: 1000
  progressLogEveryRows: 10000
  maxMergedRows:
  deleteOutputFilesAfterCompletion: false
  commonSqlFile: classpath:sql/common.sql

  sources:
    - name: db1
      jdbcUrl: ${DB1_JDBC_URL}
      username: ${DB1_USERNAME}
      password: ${DB1_PASSWORD}

  target:
    enabled: false
    jdbcUrl: ${TARGET_JDBC_URL}
    username: ${TARGET_USERNAME}
    password: ${TARGET_DB_PASSWORD}
    table: public.target_table
    truncateBeforeLoad: false
