package com.sbrf.lt.platform.ui.server

internal fun buildUiServerContext(deps: UiServerContextDependencies): UiServerContext =
    UiServerContext(
        uiConfig = deps.uiConfig,
        uiConfigLoader = deps.uiConfigLoader,
        credentialsService = deps.credentialsService,
        runtimeConfigResolver = deps.runtimeConfigResolver,
        runtimeContextService = deps.runtimeContextService,
        runtimeUiConfig = deps.runtimeUiConfig,
        runtimeContext = deps.runtimeContext,
        filesModuleBackend = deps.filesModuleBackend,
        databaseModuleStore = deps.databaseModuleStore,
        databaseModuleBackend = deps.databaseModuleBackend,
        filesRunService = deps.runManager,
        filesRunHistoryMaintenance = deps.runManager,
        configFormService = deps.configFormService,
        sqlConsoleService = deps.sqlConsoleService,
        sqlConsoleQueryManager = deps.sqlConsoleQueryManager,
        sqlConsoleExportService = deps.sqlConsoleExportService,
        sqlConsoleStateService = deps.sqlConsoleStateService,
        uiConfigPersistenceService = deps.uiConfigPersistenceService,
        moduleSyncService = deps.moduleSyncService,
        databaseModuleRunService = deps.databaseModuleRunService,
        databaseModuleActiveRunRegistry = deps.databaseModuleActiveRunRegistry,
        databaseRunHistoryCleanupService = deps.databaseRunHistoryCleanupService,
        databaseOutputRetentionService = deps.databaseOutputRetentionService,
        filesModuleRunHistoryService = deps.filesModuleRunHistoryService,
        databaseModuleRunHistoryService = deps.databaseModuleRunHistoryService,
    )
